packages:
  - "packages/*"
  - "configs/*"
  - "apps/*"
  - "docs"

catalogs:
  react:
    react: ^19.2.3
    react-dom: ^19.2.3
    "@types/react": ^19.2.7
    "@types/react-dom": ^19.2.3

  next:
    next: ^16.1.1

  typescript:
    typescript: ^5.9.2

  node:
    "@types/node": ^24.9.2

  tailwindcss:
    tailwindcss: ^4.1.18
    "@tailwindcss/postcss": ^4.1.16
